CREATE TABLE IF NOT EXISTS runs (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  run_id CHAR(36) NOT NULL,
  callsign VARCHAR(16) NOT NULL,
  score INT NOT NULL,
  time_ms INT UNSIGNED NOT NULL,
  earned INT UNSIGNED NOT NULL,
  kills INT UNSIGNED NOT NULL,
  bosses INT UNSIGNED NOT NULL,
  deaths INT UNSIGNED NOT NULL,
  deliveries INT UNSIGNED NOT NULL,
  seed BIGINT NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NULL,
  UNIQUE KEY run_id (run_id)
);

CREATE TABLE IF NOT EXISTS rate_hits (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  ip VARCHAR(45) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY ip_created (ip, created_at)
);

CREATE TABLE IF NOT EXISTS party_rooms (
  code CHAR(5) NOT NULL PRIMARY KEY,
  host_token CHAR(32) NOT NULL,
  host_peer CHAR(8) NOT NULL,
  escorts TEXT NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  touched_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY touched (touched_at)
);

CREATE TABLE IF NOT EXISTS party_signals (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  room CHAR(5) NOT NULL,
  from_peer CHAR(8) NOT NULL,
  to_peer CHAR(8) NOT NULL,
  kind VARCHAR(16) NOT NULL,
  payload TEXT NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY room_id (room, id)
);
