CREATE TABLE IF NOT EXISTS runs (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  run_id CHAR(36) NOT NULL,
  callsign VARCHAR(16) NOT NULL,
  score INT NOT NULL,
  time_ms INT UNSIGNED NOT NULL,
  earned INT UNSIGNED NOT NULL,
  kills INT UNSIGNED NOT NULL,
  bosses INT UNSIGNED NOT NULL,
  deaths INT UNSIGNED NOT NULL,
  deliveries INT UNSIGNED NOT NULL,
  seed BIGINT NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NULL,
  UNIQUE KEY run_id (run_id)
);

CREATE TABLE IF NOT EXISTS rate_hits (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  ip VARCHAR(45) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY ip_created (ip, created_at)
);
